# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  user: lottery
  database: rails_sass_membership_development
  host: localhost

test: &test
  adapter: postgresql
  encoding: utf8
  reconnect: false
  user: lottery
  database: rails_sass_membership_test
  host: localhost

cucumber:
  <<: *test


